# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OutfitCheck' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OutfitCheck
  pod 'AlamofireImage'
  pod 'Alamofire'


  target 'OutfitCheckTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OutfitCheckUITests' do
    # Pods for testing
  end

end
